-- generated by KeySteam
-- update time: 
-- app_name: Lost Castle 2 Playtest

addappid(2802060)

addtoken(2802060,"15839165981262325094")

addappid(2802061,0,"7dfc8f69006c6296eb48a3e0186c2b06ce948ca6c0774de8dd81f9083473573a")
